# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/deskblocks

HEADERS += block.h 
SOURCES += deskblocks.cpp \
           block.cpp 
TARGET=../bin/deskblocks
