# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/deskblocks

INCLUDEPATH += /usr/include/ode
LIBS += $$system(ode-config --libs)
HEADERS += block.h 
SOURCES += deskblocks.cpp \
           block.cpp
RESOURCES += deskblocks.qrc
TARGET=../bin/deskblocks
